fix for #28 with even more aggressive exception catching in initialization and checking algorithm availability so that a throwable/error such as java.lang.NoClassDefFoundError on javax.crypto.spec.GCMParameterSpec doesn’t kill everything